# -*- coding: utf-8 -*-
"""Copy of word corrector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Praysheeb/35da132c13f229b472a077af548522bc/copy-of-word-corrector.ipynb
"""

from textblob import TextBlob
words = ["Histry","phsics","chemisry"]
correct_words = []
for i in words:
    correct_words.append(TextBlob(i))
print("Wrong words :", words)
print("Correct Words are :")
for m in correct_words:
    print(m.correct(), end=" ")